version: 0.2

env:
  shell: bash
  variables:
    PACK_VOLUME_KEY: "codebuild-pack-cache"  # Consistent key for pack volume caching

# Cache configuration
cache:
  type: LOCAL
  modes:
    - LOCAL_DOCKER_LAYER_CACHE
    - LOCAL_SOURCE_CACHE
    - LOCAL_CUSTOM_CACHE
  paths:
    - '/usr/local/bin/pack'          # pack CLI binary
    - '/var/lib/docker/volumes/**/*' # Docker volumes used by pack

phases:
  install:
    commands:
      - 'echo "[install] INFO: Setting executable permissions for scripts..."'
      - chmod +x ./scripts/**/*.sh || true

      - ./scripts/01_prebuild/install_pack.sh

  pre_build:
    commands:
      - ./scripts/01_prebuild/resolve_env.sh
      - ./scripts/01_prebuild/s3_sync_and_validate.sh
      - ./scripts/01_prebuild/patch_package_json.sh
      - ./scripts/01_prebuild/process_env_files.sh
      - 'echo "[pre_build] INFO: Contents of app directory:"'
      - ls -R ./app

  build:
    commands:
      - ./scripts/02_build/build_image.sh

  post_build:
    commands:
      - ./scripts/03_postbuild/publish_sqs_message.sh

artifacts:
  files: []
