version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - echo "=== Install Cloud Native Buildpacks (pack CLI) ==="
      - curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.39.0/pack-v0.39.0-linux.tgz" | tar -C /usr/local/bin/ --no-same-owner -xzv pack
      - pack version

  pre_build:
    commands:
      - 'echo "=== Pre-build: resolve env, compute S3/ECR info, login to ECR ==="'
      - |
        # ---- Resolve AWS account & region ----
        AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-$(aws configure get region)}"

        echo "AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}"
        echo "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"
        echo "PROJECT_NAME=${PROJECT_NAME}"
        echo "USER_CODE_BUCKET=${USER_CODE_BUCKET}"
        echo "SQS_URL=${SQS_URL}"
        echo "ECR_REPO_NAME=${ECR_REPO_NAME}"
        echo "USER_ID=${USER_ID}"
        echo "FUNCTION_ID=${FUNCTION_ID}"
        echo "IMAGE_TAG=${IMAGE_TAG}"
        echo "CUSTOM_ROUTES=${CUSTOM_ROUTES}"

        # ---- Compute S3 URL & ECR repo/tag ----
        S3_URL="s3://${USER_CODE_BUCKET}/users/${USER_ID}/${FUNCTION_ID}"
        IMAGE_REPO="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPO_NAME}"
        IMAGE_TAG_FULL="${FUNCTION_ID}-${IMAGE_TAG}"
        IMAGE="${IMAGE_REPO}:${IMAGE_TAG_FULL}"

        echo "S3_URL=${S3_URL}"
        echo "IMAGE_REPO=${IMAGE_REPO}"
        echo "IMAGE_TAG_FULL=${IMAGE_TAG_FULL}"
        echo "IMAGE=${IMAGE}"

        export AWS_ACCOUNT_ID AWS_DEFAULT_REGION S3_URL IMAGE_REPO IMAGE_TAG_FULL IMAGE

      - echo "Logging in to Amazon ECR..."
      - |
        aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" \
          | docker login --username AWS --password-stdin "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"

      - echo "Syncing function source from S3..."
      - rm -rf app
      - mkdir -p app
      - aws s3 sync "${S3_URL}" ./app

      - echo "Patching package.json..."
      - cd app && python3 ../scripts/patch_package_json.py && cd ..

      - echo "Contents of app directory:"
      - ls -R ./app

  build:
    commands:
      - 'echo "=== Build: create container image with Cloud Native Buildpacks ==="'
      - 'echo "Building image: ${IMAGE}"'
      - pack build "${IMAGE}" --builder gcr.io/buildpacks/builder:latest --path ./app --pull-policy if-not-present

      - echo "Pushing image to Amazon ECR..."
      - docker push "${IMAGE}"

  post_build:
    commands:
      - 'echo "=== Post-build: send success message to SQS ==="'
      - |
        # ---- Build ECR ARN ----
        ECR_IMAGE_URI="arn:aws:ecr:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:repository/${ECR_REPO_NAME}:${IMAGE_TAG_FULL}"
        echo "ECR_IMAGE_URI=${ECR_IMAGE_URI}"
        echo "SQS_URL=${SQS_URL}"

        # ---- Build SQS message body ----
        MESSAGE_BODY="{\"userId\":\"${USER_ID}\",\"functionId\":\"${FUNCTION_ID}\",\"ecrImageArn\":\"${ECR_IMAGE_URI}\",\"customRoutes\":\"${CUSTOM_ROUTES}\"}"
        echo "Sending message to SQS: ${MESSAGE_BODY}"

        aws sqs send-message \
          --queue-url "${SQS_URL}" \
          --message-body "${MESSAGE_BODY}"

artifacts:
  files: []
