version: 0.2

env:
  variables:
    IMAGE_TAG: latest
    SQS_QUEUE_URL: "https://sqs.ap-northeast-2.amazonaws.com/900253478827/cutty-x-infra-dev-faas-result-queue"

phases:
  install:
    commands:
      - echo "Installing pack CLI..."
      - curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.39.0/pack-v0.39.0-linux.tgz" | tar -C /usr/local/bin/ --no-same-owner -xzv pack
      - pack version
      - python3 --version

  pre_build:
    commands:
      - echo "Syncing user function code from S3..."
      - mkdir -p app
      - aws s3 sync "s3://${USER_CODE_BUCKET}/${FUNCTION_S3_PREFIX}" ./app
      - echo "Patching package.json..."
      - cd app && python3 ../scripts/patch_package_json.py && cd ..
      - echo "Authenticating to Amazon ECR..."
      - aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" | docker login --username AWS --password-stdin "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
      - export IMAGE="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/codebuild-test-repo:${FUNCTION_ID}-${IMAGE_TAG}"
      - echo "Target image:${FUNCTION_ID}-${IMAGE_TAG}"

  build:
    commands:
      - echo "Building Docker image with Cloud Native Buildpacks..."
      - pack build "${IMAGE}" --builder gcr.io/buildpacks/builder:latest --path ./app --pull-policy if-not-present

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push "${IMAGE}"
      - echo "Build complete. Image:${FUNCTION_ID}-${IMAGE_TAG}"
      - echo "Sending message to SQS queue..."
      - |
      aws sqs send-message \
        --queue-url "${SQS_QUEUE_URL}" \
        --message-body "{
          \"user_id\": \"${USER_ID}\",
          \"function_id\": \"${FUNCTION_ID}\",
          \"ecr_image_arn\": \"${IMAGE_ARN}\",
          \"endpoint\": \"${ENDPOINT}\"
        }"
      - echo "SQS message sent."


artifacts:
  files:
    - "**/*"